name: 'Deploy Glue Job'

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
    - 'jobs/**'

jobs:

  deploy_glue_jobs:
    permissions:
      actions: write
      contents: write
    
    runs-on: ubuntu-latest
    environment: pdn

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: 'Upload to S3 Bucket'
        run: aws s3 cp jobs/gh_archive_curate_data.py s3://${{ secrets.AWS_S3_BUCKET_NAME }}/${{ secrets.AWS_S3_BUCKET_KEY }}
